#!/usr/bin/env python3
"""Auto-generate root index.md by scanning sub-project OKF docs.

Usage:
  python scripts/update_index.py           # Generate index.md
  python scripts/update_index.py --check   # Check only, report drift
"""

import os, sys, argparse, subprocess
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = ROOT / "index.md"

HEADER = "| Module | Docs | Types | Entry |"
SEP    = "|--------|------|-------|-------|"
DETAIL_HEADER = "| Type | Title | Path | Updated |"
DETAIL_SEP    = "|------|-------|------|---------|"

GIT_DATE_MARK = "@@COMMIT@@"


def git_dates(root: Path) -> dict:
    """Map repo-relative path -> last commit date (YYYY-MM-DD), newest commit wins.

    One `git log` pass instead of one call per file. Falls back to {} when git is
    unavailable or the repo has no history, in which case callers use file mtime.

    Why git dates and not mtime: mtime is the *checkout* time on a fresh clone or
    worktree, so every file looks freshly edited and the whole index churns on
    each checkout. The commit date is stable across machines.
    """
    try:
        out = subprocess.run(
            ["git", "log", f"--format={GIT_DATE_MARK}%ad", "--name-only", "--date=short"],
            cwd=root, capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=120,
        ).stdout
    except Exception:
        return {}

    dates: dict = {}
    current = None
    for line in out.splitlines():
        if line.startswith(GIT_DATE_MARK):
            current = line[len(GIT_DATE_MARK):].strip()
        elif line.strip() and current:
            # git log is newest-first, so the first sighting is the latest commit
            dates.setdefault(line.strip(), current)
    return dates


def scan(root: Path, dates: dict) -> dict:
    modules = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")
                       and d not in ("node_modules","__pycache__","data","out","venv",".venv",".git")]
        for fname in filenames:
            if not fname.endswith(".md"):
                continue
            fpath = Path(dirpath) / fname
            try:
                content = fpath.read_text(encoding="utf-8")
            except Exception:
                continue
            if not content.startswith("---"):
                continue
            end = content.find("---", 3)
            if end == -1:
                continue
            fm_text = content[3:end].strip()
            # 逐行匹配键名, 不能用 `"type:" in fm_text` —— 那会把
            # `problem_type:` / `component_type:` 这类**含 type 子串的别的键**
            # 误判成 type 字段, 于是「缺 type 的文件」也被当成合规文档计入。
            fm_lines = [ln.strip() for ln in fm_text.split("\n")]
            has_okf = any(ln.startswith("okf:") for ln in fm_lines)
            has_type = any(ln.startswith("type:") for ln in fm_lines)
            if not (has_okf or has_type):
                continue
            meta = {}
            for line in fm_text.split("\n"):
                line = line.strip()
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip()] = v.strip().strip('"').strip("'")
            rel_dir = Path(dirpath).relative_to(root).as_posix()
            rel_path = fpath.relative_to(root).as_posix()
            parts = rel_dir.split("/")
            module = parts[0] if parts[0] != "." else "root"
            # commit date when the file is tracked; mtime for new/untracked files
            mtime = dates.get(rel_path) or datetime.fromtimestamp(
                fpath.stat().st_mtime).strftime("%Y-%m-%d")
            modules.setdefault(module, []).append({
                "path": rel_path, "type": meta.get("type","?"),
                "title": meta.get("title", fname), "okf": meta.get("okf",""),
                "mtime": mtime,
            })
    return modules


def build(modules: dict) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "---",
        "okf: v0.1",
        "type: Index",
        "title: fzh-data - Project Doc Index",
        "description: Auto-generated index of sub-project OKF docs. Generated by scripts/update_index.py.",
        f"generated: {now}",
        "---",
        "",
        "# fzh-data Project Doc Index",
        "",
        "> Auto-generated by `scripts/update_index.py`. Do not edit manually.",
        f"> Last updated: {now}",
        "",
        "## Sub-Projects",
        "",
        HEADER,
        SEP,
    ]
    for mod in sorted(modules.keys()):
        docs = modules[mod]
        types = sorted(set(d["type"] for d in docs))
        index_doc = next((d for d in docs if d["type"] == "Index"), None)
        entry = (index_doc or docs[0])["path"]
        lines.append(f"| **{mod}** | {len(docs)} | {', '.join(types[:4])} | [{mod}/]({mod}/) -> [{entry}]({entry}) |")
    lines.extend(["", "## Module Details", ""])
    for mod in sorted(modules.keys()):
        docs = modules[mod]
        lines.append(f"### {mod}")
        lines.append("")
        lines.append(DETAIL_HEADER)
        lines.append(DETAIL_SEP)
        for d in sorted(docs, key=lambda x: (x["type"], x["title"])):
            lines.append(f"| {d['type']} | {d['title']} | [{d['path']}]({d['path']}) | {d['mtime']} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Update root index.md")
    parser.add_argument("--check", action="store_true", help="Check only, report drift")
    args = parser.parse_args()
    modules = scan(ROOT, git_dates(ROOT))
    content = build(modules)
    if args.check:
        if INDEX_PATH.is_file():
            existing = INDEX_PATH.read_text(encoding="utf-8")
            if existing == content:
                print("OK: index.md is up to date")
            else:
                print("STALE: index.md is outdated. Run: python scripts/update_index.py")
                sys.exit(1)
        else:
            print("MISSING: index.md not found. Run: python scripts/update_index.py")
            sys.exit(1)
    else:
        INDEX_PATH.write_text(content, encoding="utf-8")
        total = sum(len(v) for v in modules.values())
        print(f"Generated: {INDEX_PATH}")
        print(f"  Modules: {len(modules)}")
        print(f"  Docs: {total}")


if __name__ == "__main__":
    main()
