#!/usr/bin/env python3
"""Auto-generate root index.md by scanning sub-project OKF docs.

Usage:
  python scripts/update_index.py           # Generate index.md
  python scripts/update_index.py --check   # Check only, report drift
"""

import os, sys, argparse
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = ROOT / "index.md"

HEADER = "| Module | Docs | Types | Entry |"
SEP    = "|--------|------|-------|-------|"
DETAIL_HEADER = "| Type | Title | Path | Updated |"
DETAIL_SEP    = "|------|-------|------|---------|"


def scan(root: Path) -> dict:
    modules = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")
                       and d not in ("node_modules","__pycache__","data","out","venv",".venv",".git")]
        for fname in filenames:
            if not fname.endswith(".md"):
                continue
            fpath = Path(dirpath) / fname
            try:
                content = fpath.read_text(encoding="utf-8")
            except Exception:
                continue
            if not content.startswith("---"):
                continue
            end = content.find("---", 3)
            if end == -1:
                continue
            fm_text = content[3:end].strip()
            has_okf = "okf:" in fm_text
            has_type = "type:" in fm_text
            if not (has_okf or has_type):
                continue
            meta = {}
            for line in fm_text.split("\n"):
                line = line.strip()
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip()] = v.strip().strip('"').strip("'")
            rel_dir = Path(dirpath).relative_to(root).as_posix()
            rel_path = fpath.relative_to(root).as_posix()
            parts = rel_dir.split("/")
            module = parts[0] if parts[0] != "." else "root"
            mtime = datetime.fromtimestamp(fpath.stat().st_mtime).strftime("%Y-%m-%d")
            modules.setdefault(module, []).append({
                "path": rel_path, "type": meta.get("type","?"),
                "title": meta.get("title", fname), "okf": meta.get("okf",""),
                "mtime": mtime,
            })
    return modules


def build(modules: dict) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "---",
        "okf: v0.1",
        "type: Index",
        "title: fzh-data - Project Doc Index",
        "description: Auto-generated index of sub-project OKF docs. Generated by scripts/update_index.py.",
        f"generated: {now}",
        "---",
        "",
        "# fzh-data Project Doc Index",
        "",
        "> Auto-generated by `scripts/update_index.py`. Do not edit manually.",
        f"> Last updated: {now}",
        "",
        "## Sub-Projects",
        "",
        HEADER,
        SEP,
    ]
    for mod in sorted(modules.keys()):
        docs = modules[mod]
        types = sorted(set(d["type"] for d in docs))
        index_doc = next((d for d in docs if d["type"] == "Index"), None)
        entry = (index_doc or docs[0])["path"]
        lines.append(f"| **{mod}** | {len(docs)} | {', '.join(types[:4])} | [{mod}/]({mod}/) -> [{entry}]({entry}) |")
    lines.extend(["", "## Module Details", ""])
    for mod in sorted(modules.keys()):
        docs = modules[mod]
        lines.append(f"### {mod}")
        lines.append("")
        lines.append(DETAIL_HEADER)
        lines.append(DETAIL_SEP)
        for d in sorted(docs, key=lambda x: (x["type"], x["title"])):
            lines.append(f"| {d['type']} | {d['title']} | [{d['path']}]({d['path']}) | {d['mtime']} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Update root index.md")
    parser.add_argument("--check", action="store_true", help="Check only, report drift")
    args = parser.parse_args()
    modules = scan(ROOT)
    content = build(modules)
    if args.check:
        if INDEX_PATH.is_file():
            existing = INDEX_PATH.read_text(encoding="utf-8")
            if existing == content:
                print("OK: index.md is up to date")
            else:
                print("STALE: index.md is outdated. Run: python scripts/update_index.py")
                sys.exit(1)
        else:
            print("MISSING: index.md not found. Run: python scripts/update_index.py")
            sys.exit(1)
    else:
        INDEX_PATH.write_text(content, encoding="utf-8")
        total = sum(len(v) for v in modules.values())
        print(f"Generated: {INDEX_PATH}")
        print(f"  Modules: {len(modules)}")
        print(f"  Docs: {total}")


if __name__ == "__main__":
    main()
